### ISSUE TITLE
Magic Padding Oracle (PicoCTF2018)

### ISSUE THREAD

**Issue by solomonbstoner** [solomonbstoner/solomonbston3r-ctf-diary#8]
When my code tries to modify the plaintext of the cipher, I get thrown the error `PaddingOracleException('Cipher size is not block size: 6 != 16')`. I do not know why it would ever be 6, but I'll find out why.

In `padding_oracle.py`:
```
    def decrypt_block(self, iv_block, cipher_block, pre_known=[], detect_padding=False, optimized_alphabet=printable_ascii_alphabet()):
        """
        Decrypts a single cipher block.
        """
        [...]
        if len(cipher_block)//2 != self.block_size:
            raise PaddingOracleException('Cipher size is not block size: {} != {}'.format(len(cipher_block)//2, self.block_size))
```

`decrypt_block` is called by `craft`, so it is a good place to look. I think the problem lies with `cipher_new_blocks[0]`. To be investigated.

In `padding_oracle.py`'s `craft` function:
```
            if nothing_changed_yet:
                print('block{} changed!'.format(i))
                cipher_new_block = int_array_to_hex([(a ^ b ^ c) for a, b, c in zip(plain_old_block, plain_new_block, hex_to_int_array(iv))])
                cipher_new_blocks.insert(0, cipher_new_block)
                
                nothing_changed_yet = False
```

**Comment by solomonbstoner** [comment]
The error described above is:
```
➜  magic_padding_oracle git:(master) ✗ python3 soln.py
b'{"username": "admin", "expires": "3000-01-07", "is_admin": "true" }'
block5 changed!
['5a80c37e7f99', '5ab1726c337c128163c4c3449ce2398d']
crafting new block4...
['5a80c37e7f99', '5ab1726c337c128163c4c3449ce2398d']
Traceback (most recent call last):
  File "soln.py", line 43, in <module>
    cipher_new = o.craft(cipher, plain, plain_new)
  File "/home/solomonbstoner/Documents/Scr3enSl4y3rs/picoCTF_2018/Cryptography/magic_padding_oracle/padding_oracle.py", line 172, in craft
    _, intermediate, _ = self.decrypt_block(hex_to_int_array(iv), cipher_new_blocks[0])
  File "/home/solomonbstoner/Documents/Scr3enSl4y3rs/picoCTF_2018/Cryptography/magic_padding_oracle/padding_oracle.py", line 48, in decrypt_block
    raise PaddingOracleException('Cipher size is not block size: {} != {}'.format(len(cipher_block)//2, self.block_size))
padding_oracle.PaddingOracleException: Cipher size is not block size: 6 != 16
```
It is reproduced when there is a space between `"is_admin": "true"` and `}'` (ie `"is_admin": "true" }'`). I tested and confirmed the hypothesis using the following 2 codes:
1. `plain_new = b'{ "username": "admin", "expires": "3000-01-07", "is_admin": "true" }'`
2. 
``` 
plain = b'{"username": "guest", "expires": "2000-01-07", "is_admin": "false"}'
plain_new = plain[:34] + b'30' + plain[36:60] + b'true" ' + plain[66:]
```

**Comment by solomonbstoner** [comment]
Compare the 2 different snippets of output. Outputs 1 & 2 show different byte for Byte 8 of Block 3. I suspect Output 1's is wrong. That probably resulted in the infinite loop in Byte 7 as since Byte 8 is wrong, Byte 7 would never be found. In contrast, Byte 8 from Output 2 is probably correct. Thus, it found Byte 7 just fine.

Is it possible to make a change to the code to make it search for Byte 8 again when it finds out there is no correct value for Byte 7?

### Output 1
```
crafting new block3...
['41acaa847ff3f742a8aaa7c810045857', '1d82c37e7f991be60eda932d1fd407c6', '5ab1726c337c128163c4c3449ce2398d']
Byte 16:
................................................................................................................. 0xf3
Byte 15:
............................................................................................................................................................................................................................... 0x85
Byte 14:
................................................................................................................................. 0xe3
Byte 13:
........................................................................................................................................................................................................................................................ 0x08
Byte 12:
.. 0x31
Byte 11:
.................. 0x68
Byte 10:
.................................................................................................................. 0xf2
Byte 09:
........................................................................................................................................................................................................................................ 0x1d
Byte 08:
.... 0x33
Byte 07:
.........................E...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Traceback (most recent call last):
  File "soln.py", line 45, in <module>
    cipher_new = o.craft(cipher, plain, plain_new)
```

### Output 2
```
['41acaa847ff3f742a8aaa7c810045857', '1d82c37e7f991be60eda932d1fd407c6', '5ab1726c337c128163c4c3449ce2398d']
crafting new block3...
['41acaa847ff3f742a8aaa7c810045857', '1d82c37e7f991be60eda932d1fd407c6', '5ab1726c337c128163c4c3449ce2398d']
Byte 16:
................................................................................................................. 0xf3
Byte 15:
............................................................................................................................................................................................................................... 0x85
Byte 14:
................................................................................................................................. 0xe3
Byte 13:
........................................................................................................................................................................................................................................................ 0x08
Byte 12:
.. 0x31
Byte 11:
.................. 0x68
Byte 10:
.................................................................................................................. 0xf2
Byte 09:
........................................................................................................................................................................................................................................ 0x1d
Byte 08:
..................... 0x6b
Byte 07:
............................... 0x75
Byte 06:
```

**Comment by solomonbstoner** [comment]
Wont fix outdated challenge. Closing
